const mongoose = require('mongoose');
const stationSchema = new mongoose.Schema({
    
    ownerId:{
        type:String,
        required:true,
    },
    ownerName:
    {
        type:String,
        required:true,      
    },
    StationName:{
        type:String,
        required:true
    },
    ContactNo:{
        type:String,
        required:true
    },
    address:{
        type:String,
        unique:true,
        required:true
    },
    city:{
        type:String,
        required:true,     
    },
    pincode:{
        type:Number,
        required:true,
    },
    state:{
        type:String,
        required:true
    },
     plug1:
     {
        type:String,
        required:true
    },
    Plug2:{
        type:String,
        required:true
    },
    openingTime:{
        type:String,
        required:true
    },
    closeTime:{
        type:String,
        required:true
    },
    Latitude:{
        type:Number,
        required:true
    },
    Longitude:
    {
        type:Number,
        required:true
    },
    Image:{
        type:String,
        required:true
    },
    rating:{
        type:Number,
        required:true
    },
    review:{
        type:Number,
        required:true
    },
    Location:{
        type:String,
        required:true
    },
}
 
)
mongoose.model('station',stationSchema);